name: "Chromatic Deployment"

on: push

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout latest commit
              uses: actions/checkout@v1

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                node-version: '16'
                cache: 'npm'
                cache-dependency-path: '**/package-lock.json'

            - name: Install npm dependencies
              run: npm install

            - name: Deploy to Chromatic
              uses: chromaui/action@v1
              with:
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
                  token: ${{ secrets.GITHUB_TOKEN }}
